In [ ]:
import time
import sys
import numpy as np


sys.setrecursionlimit(1000000000)

In [ ]:
a = np.random.randn(3,3)

b = np.random.randn(3, 1)


c = a*b

print(c)

[[-0.40409982 -0.20736822 -0.30789264]
 [-2.7511992   0.78910626 -4.49062677]
 [-0.14082723  0.11231691  0.05453974]]


In [ ]:


def factorial_r(n):
    if n == 0 or n == 1:
        return 1
    return n * factorial_r(n-1)

def factorial_for(n):
    if n == 0 or n == 1:
        return 1
    acumulador = 1
    for i in range(1,n+1):
        acumulador *= i
    return acumulador




if __name__ == "__main__":
    beginning = time.time()
    factorial_r(1000)
    step_1 = time.time()
    factorial_for(100)
    step_2 = time.time()
    print(step_1 - beginning)
    print(step_2 - step_1)



3.170967102050781e-05
1.1205673217773438e-05


In [ ]:
def f(x):

    respuesta = 0
 
    for i in range(1000):  # Equivale a : 1000
        respuesta += 1     # Equivale a : 1     - Unidad mínima para calcular la complejidad de este algoritmo

    for i in range(x):     # Equivale a : n
        respuesta += x     # Equivale a : 1

    for i in range(x):     # Equivale a : 2n^2
        for i in range(x): # Equivale a : 2n
            respuesta += 1 # Equivale a : 1
            respuesta += 1 # Equivale a : 1

    return respuesta